### PR TITLE
declare 3 features for MVP in README

### PR DESCRIPTION
**Pull request by jonathanhinton**
This PR is created to declare the 3 features agreed upon for MVP.

### CODE REVIEW

**Comment by rousell** [comment]
This looks good!

**Comment by jonathanhinton** [comment]
@jcockhren @AdamSheaffer I added the 3 features our team agreed upon for MVP. Take a look and let me know what you think. Thanks

**Comment by jcockhren** [comment]
@jonathanhinton Your list isn't rendering as a list.

See -> https://github.com/jcockhren/e2-monitor-the-web/blob/README_features/README.md

**Comment by jonathanhinton** [comment]
@jcockhren I fixed markdown so the features read as a list.  Thanks for the link.

**Comment by alihamsa** [comment]
I was here.

**Comment by jcockhren** [comment]
@jonathanhinton :+1:

**Comment by AdamSheaffer** [comment]
Looks good :metal:

**Pull request merged**
